server:
  port: 9090
spring:
  application:
    name: teach-service
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      discovery:
        namespace: cc4b2bda-cc4e-48f5-acfa-151dc7b9b1ea
        group: A_GROUP
        service: teach-service
