server:
  port: 8989
spring:
  application:
    name: login-service
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      discovery:
        namespace: cc4b2bda-cc4e-48f5-acfa-151dc7b9b1ea
        group: A_GROUP
        service: login-service
  redis:
    host: 192.168.111.100
    port: 6379
    database: 1


